### ISSUE TITLE
docs: where the '192.0.2.1/24' in the "Get started with MicroCloud" comes from ?

### ISSUE THREAD

**Issue by padoauk** [canonical/microcloud#499]
In the document of "Tutorial > Getting started with MicroCloud", '192.0.2.1/24'' suddenly appears as uplink network gateway address. Where this value(address) should come from ? Since the uplink network interface can be selected from those which has no IP address attached in microcloud init procedure, it looks like arbitrarily chosen. But in that case, I doubt that it works as gateway to uplink network.

---
*Reported from: https://canonical-microcloud.readthedocs-hosted.com/en/latest/microcloud/tutorial/get_started/

**Comment by padoauk** [comment]
Thank you for replay. Now I've got to know what are necessary to prepare for successful `microcloud init` so that I can understand the documents much more easy. But for those who read for the first time, what about insert example results of `ip a s`, `lsblk` after 5.3 of the "Getting started Microcloud" ?

**Comment by roosterfish** [comment]
> For such readers, examples showing after 5.3 can be skipped.

The tutorial is meant to be followed from the beginning to the end so that you have a bulletproof example that shows you how to deploy everything from scratch.

In case of the uplink network that is something we cannot influence, therefore we have picked an example IP range. But I see another occasion where the confusion might be coming from. I suggest we update the step where you run `lxd init` to set a specific subnet which then matches the rest of the tutorial.

In your case (deploying on bare metal) the installation is covered by [How to install MicroCloud
](https://canonical-microcloud.readthedocs-hosted.com/en/latest/microcloud/how-to/install/) and the intialisation in the follow up guide [How to initialise MicroCloud](https://canonical-microcloud.readthedocs-hosted.com/en/latest/microcloud/how-to/initialise/). 
So you instead of the Tutorial you would follow the [How-to guides](https://canonical-microcloud.readthedocs-hosted.com/en/latest/microcloud/how-to/) which also have pages on updating MicroCloud.
